import FWCore.ParameterSet.Config as cms

#ideal geometry
XMLIdealGeometryESSource = cms.ESSource("XMLIdealGeometryESSource",
    geomXMLFiles = cms.vstring('Geometry/CMSCommonData/data/materials.xml',
        'Geometry/CMSCommonData/data/rotations.xml', 
 	    'Geometry/CMSCommonData/data/extend/cmsextent.xml',
        'Geometry/CMSCommonData/data/cms.xml', 
        'Geometry/CMSCommonData/data/PhaseI/beampipe.xml', 
        'Geometry/CMSCommonData/data/cmsBeam.xml', 
        'Geometry/CMSCommonData/data/cmsMother.xml', 
        'Geometry/CMSCommonData/data/mgnt.xml', 
        'Geometry/ForwardCommonData/data/forward.xml', 
        'Geometry/ForwardCommonData/data/totemRotations.xml', 
        'Geometry/ForwardCommonData/data/totemMaterials.xml', 
        'Geometry/ForwardCommonData/data/totemt1.xml', 
        'Geometry/ForwardCommonData/data/totemt2.xml', 
        'Geometry/ForwardCommonData/data/ionpump.xml', 
        'Geometry/VeryForwardData/data/RP_Box.xml',
        'Geometry/VeryForwardData/data/RP_Box/RP_Box_002.xml',
        'Geometry/VeryForwardData/data/RP_Box/RP_Box_003.xml',
        'Geometry/VeryForwardData/data/RP_Box/RP_Box_102.xml',
        'Geometry/VeryForwardData/data/RP_Box/RP_Box_103.xml',
        'Geometry/VeryForwardData/data/RP_Hybrid.xml',
        'Geometry/VeryForwardData/data/RP_Materials.xml',
        'Geometry/VeryForwardData/data/RP_Transformations.xml',
        'Geometry/VeryForwardData/data/RP_Detectors_Assembly.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Pixel_Assembly_Box_Real_002.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Pixel_Assembly_Box_Real_003.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Pixel_Assembly_Box_Real_102.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Pixel_Assembly_Box_Real_103.xml',
        'Geometry/VeryForwardData/data/RP_Device.xml',
        'Geometry/VeryForwardData/data/RP_Horizontal_Device.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Pixel_Positive_Station.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Pixel_Negative_Station.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Stations_Assembly.xml',
        'Geometry/VeryForwardData/data/RP_Sensitive_Dets.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Cuts_Per_Region.xml',
        'Geometry/CTPPSCommonData/data/ppstrackerMaterials.xml',
        'Geometry/CTPPSCommonData/data/CTPPSPixelModule.xml',
        'Geometry/CTPPSSimData/data/CTPPSPixelsens.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Materials.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Transformations.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Horizontal_Pot.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbar.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_A13.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_A24.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_B13.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_B24.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_C13.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_C24.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_D13.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_D24.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_E13.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Lbars/CTPPS_Timing_Lbar_E24.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Box_Negative.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Box_Positive.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Negative_Detector_Assembly.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Positive_Detector_Assembly.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Negative_Station.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Positive_Station.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_Timing_Stations_Assembly.xml',
        'Geometry/CTPPSCommonData/data/CTPPS_XDistance_From_Beam.xml'
),
    rootNodeName = cms.string('cms:CMSE')
)
XMLIdealGeometryESSource.geomXMLFiles.append("Geometry/VeryForwardData/data/2016_ctpps_15sigma_margin0/RP_Dist_Beam_Cent.xml")
# real geometry
TotemRPGeometryESModule = cms.ESProducer("TotemRPGeometryESModule",
    verbosity = cms.untracked.uint32(3)
)
